version: '2.1'
services:
  redis:
   image: redis
   volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
   ports:
      - 6379:6379  
   command: redis-server --appendonly yes
  mongo:
   image: mongo
   volumes: 
      - ~/data/db:/data/db 
   ports:
      - 27017:27017
   command: mongod --auth
  tim:
    image: tim
    build: ./Tim
    environment:
      NODE_ENV: ${DEV_ENV}
    restart: always
    links:
      - redis
      - mongo
    depends_on:
      - mongo
    ports:
      - 8888:8888
  nginx:
    image: nginx_tim
    build: ./nginx
    ports:
      - 8866:8866  
      - 80:80  
    links:
      - tim
