version: '2.1'

services:
  redis:
   image: redis
   volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - ./data:/data  
   networks:
      - back-tier
   ports:
      - 6379:6379  
   command: redis-server --appendonly yes
  mongo:
   image: mongo
   networks:
      - back-tier
   volumes: 
      - ~/data/db:/data/db 
   ports:
      - 27017:27017
  tim:
    image: tim
    build: ./Tim
    environment:
      NODE_ENV: ${DEV_ENV}
    restart: always
    links:
      - redis
      - mongo
    depends_on:
      - mongo
    ports:
      - 8888:8888  
    networks:
      - back-tier
networks:
  back-tier:
    driver: bridge